# Generated by Django 4.1.2 on 2022-11-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_interscholar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bert',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('content_revised', models.TextField()),
                ('attachment_url', models.CharField(blank=True, max_length=400, null=True)),
                ('attachment_content', models.TextField(blank=True, null=True)),
                ('content_url', models.CharField(max_length=400)),
                ('department', models.CharField(max_length=100)),
                ('con_age', models.CharField(blank=True, max_length=200, null=True)),
                ('con_bef_score', models.CharField(blank=True, max_length=200, null=True)),
                ('con_total_score', models.CharField(blank=True, max_length=200, null=True)),
                ('con_income', models.CharField(blank=True, max_length=200, null=True)),
                ('con_major', models.CharField(blank=True, max_length=200, null=True)),
                ('con_where', models.CharField(blank=True, max_length=200, null=True)),
                ('con_end_date', models.CharField(blank=True, max_length=200, null=True)),
                ('con_special', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'bert',
                'managed': False,
            },
        ),
    ]
