# Generated by Django 4.1.2 on 2022-11-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_bertt_delete_bert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('date', models.TextField()),
                ('content', models.TextField()),
                ('content_revised', models.TextField()),
                ('attachment_url', models.CharField(blank=True, max_length=400, null=True)),
                ('attachment_content', models.TextField(blank=True, null=True)),
                ('content_url', models.CharField(max_length=400)),
                ('department', models.CharField(max_length=100)),
                ('con_age', models.CharField(blank=True, max_length=200, null=True)),
                ('con_bef_score', models.CharField(blank=True, max_length=200, null=True)),
                ('con_total_score', models.CharField(blank=True, max_length=200, null=True)),
                ('con_income', models.CharField(blank=True, max_length=200, null=True)),
                ('con_major', models.CharField(blank=True, max_length=200, null=True)),
                ('con_where', models.CharField(blank=True, max_length=200, null=True)),
                ('con_end_date', models.CharField(blank=True, max_length=200, null=True)),
                ('con_special', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bertt',
        ),
    ]
